<div style="display: flex;">
    <div style="flex: 1;">
        <h1>Aprendizaje computacional 2023</h1>
        <h2>Unidad 3 - Métodos paramétricos</h2>
        <p><strong>Nombre:</strong> David Aaron Ramirez Olmeda<br>
        <strong>Programa:</strong> Maestría en Ciencia de Datos e Información</p>
    </div>
    <img src="https://pbs.twimg.com/profile_images/1674912653049774081/Lj1u22X8_400x400.jpg" alt="Imagen de Portada" width="170" height="170">
</div>

In [4]:
from EvoMSA.model import GaussianBayes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer, load_diabetes
from scipy.stats import norm, multivariate_normal
from scipy.special import logsumexp
from matplotlib import pylab as plt
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_theme()
import os
from sklearn import metrics

In [14]:
T = np.loadtxt('delitos/delitos_train_data.csv', delimiter=',')
y_t = np.loadtxt('delitos/delitos_train_label.csv', delimiter=',')
G = np.loadtxt('delitos/delitos_test_data.csv', delimiter=',')
y_g = np.loadtxt('delitos/delitos_test_label.csv', delimiter=',')

gaussian = GaussianBayes().fit(T, y_t)
naive = GaussianBayes(naive=True).fit(T, y_t)

hy_gaussian = gaussian.predict(G)
hy_naive = naive.predict(G)

error_gaussian = (y_g != hy_gaussian).mean()
error_naive = (y_g != hy_naive).mean()

error_gaussian

error_naive

diff = (y_g != hy_naive).mean() -  (y_g != hy_gaussian).mean()

S = np.random.randint(y_g.shape[0],
                      size=(500, y_g.shape[0]))
B = [(y_g[s] != hy_naive[s]).mean() -  (y_g[s] != hy_gaussian[s]).mean()
     for s in S]
se = np.std(B, axis=0)

sns.displot(B, kde=True)

/Users/aaron/opt/anaconda3/lib/python3.9/site-packages/EvoMSA/model.py:634: RuntimeWarning: invalid value encountered in subtract
  return posterior - evidence


In [16]:
dist = norm(loc=diff, scale=se)
dist.cdf(0)

0.28670938128208057

In [17]:
accuracy = metrics.accuracy_score(y_g, hy_naive)

In [18]:
recall = metrics.recall_score(y_g, hy_naive, average=None)
precision = metrics.precision_score(y_g, hy_naive, average=None)
f1 = metrics.f1_score(y_g, hy_naive, average=None)

In [22]:
f1

array([0.84046693, 0.60194175])

In [21]:
precision

array([0.93913043, 0.47692308])

In [20]:
recall

array([0.76056338, 0.81578947])

In [19]:
accuracy

0.7722222222222223

In [34]:
import numpy as np

# Encuentra las filas con valores NaN en G
nan_rows = np.isnan(G).any(axis=1)

# Filtra G y y_g para eliminar las filas con NaN
G_clean = G[~nan_rows]
y_g_clean = y_g[~nan_rows]

# Filtra las predicciones para que coincidan con los datos limpios
prob_clean = prob[~nan_rows]

# Verifica si hay valores NaN o infinitos en las predicciones limpias
if np.isnan(prob_clean).any() or np.isinf(prob_clean).any():
    # Si se encuentran valores problemáticos, realiza un manejo adecuado, como imputación o eliminación.
    # También puedes investigar por qué se están generando valores problemáticos en tus predicciones.
    print("Se encontraron valores NaN o infinitos en las predicciones limpias.")
else:
    # Si no hay valores problemáticos, procede con el cálculo de la entropía cruzada.
    entropia = metrics.log_loss(y_g_clean, prob_clean)


Se encontraron valores NaN o infinitos en las predicciones limpias.
